export const dataKoass = (): string[] => [
  "Hey\n(click here!)",
  "I know coass can be hard",
  "I mean really really hard",
  "It can be overwhelming",
  "so much stuff to learn",
  "with a really packed schedule :(",
  "(kacian cewe aku :( )",
  "...",
  "Well actually I probably don't even know that much",
  "I never went to med school, and I didn't actually go through what you went through",
  "...",
  "But having the privilege to see you everyday",
  "Accompannying you",
  "And be by your side..",
  "has made me believe that it's probably one of the most difficult thing to do in this world.",
  "soo,",
  "I'm sorry I cannot be there to support you",
  "to help you",
  "or to protect you",
  "and sometimes maybe I cannot fully truly understand what is it that you went through..",
  "or even relate to you..",
  "But..",
  "I want you to know",
  "That I really really want to do all that",
  "I want to support you",
  "I want to protect you",
  "And most importantly,",
  "I want you to know that I want to try my best to understand you",
  "You and everything that you have went through",
  "I wanna be there for you",
  "I want you to know that you have me",
  "I want you to know that I'm here",
  "I hope I can do all that",
  "I tried my best and will try to be better too!",
  "...",
  "I'm grateful that you always tried to share your day with me",
  "sharing your bad day too",
  "it is always nice to be able to hear your vent too",
  "It's like I'm getting to know you better",
  "It's like getting to know the REAL you",
  "And that's what I want",
  "So I'm grateful for all of that",
  "For us",
  "For the team we are",
  "I'm happy you're my partner",
  "Thanks for letting me be yours",
  "I love you",
  "Oh ya, I made this thing so that when you click on my face right there, It will pop out some sentences that I hope can put a smile on your face :)",
  "Try It!",
];
