export const motivations = (): string[] => [
  "I love you so much bby ❤️",
  "Aku suka banget rasa care kamu ke orang2 sekitar kamu.. meskipun segala kehectican yg kamu lg hadapin :(",
  "Manasih ini yang ganggu kamu!! >:((",
  "Manasih ini yang bikin cewe aku kecapean!! sini lu!! >:((",
  "sayang aku, kenapa? :( call yukk",
  "Babe you are so special to me I love you so much",
  "Cheer up sayang! I’m soo proud of my amazing girlfriend :D",
  "Aku bersyukur bisa ngobrol sama kamu tiap hari :) aku suka itu",
  "Mungkin aku jarang bilang,, tapi aku suka banget mata kamu. mata kamu cantik banget :)",
  "I love you so much bby <3",
  "7 September 2022 itu hari yang paling aku tak sesali… aku bersyukur bgt bisa punya partner kyk kamu",
  "Happy 7 September!! (ini hari raya kita doang haha)",
  "Cheer up sayang aku :D",
  "Aku suka banget hubungan kitaa,, aku suka banget kita bisa doa bareng hehe mnrt aku gemes",
  "Makasih ya sayang udah selalu coba ngertiin aku… bahkan pas aku emotional aja kamu ttp suka 🥺 itu special bgt buat aku.. kamu special",
  "Cewek aku udah baik, lucu, cakep (banget), attractive, pinter, jago ini itu, banyak banget dehhh kelebihannya!",
  "I love you like a mountain rain.. like a hurricane 🎶.. tebak aku nyanyi apa",
  "Best partner and girlfriend of the year goes too… (jeng jeng)… Trisha!!!",
  "Mata kamu ngelengkung, aku suka liatinnya",
  "I want to take a moment to appreciate all the wholesome reels you've shared to me :)",
  "Kyknya iya deh aku kesemsem sm kamu… Tapi kalo orangnya se keren kamu, wajar jg sih aku kesemsem",
  "Babe I’m so grateful bisa sm kamu… aku selalu merasa loved pas kamu bangunin aku (berkali2 bahkan hehe)",
  "You’ve done your best baby!! Aku selalu liat kamu mengerjakan semuanya pake hati kamu!!",
  "Yuk jangan nyerah yuk biar kita bisa bareng2 terus!! yuk",
  "we’re a team! please know I’m on your side babe",
  "Let’s pursue all those things that are more important than fear! let’s be courageous together!!",
  "Thanks for sharing your views about content and what it means to be happy while being content at the same time :)",
  "Kamu punya alasan untuk jadi dokter yang menurut aku indah sekali sha :) aku yakin kamu bisa <3",
  "Any and every day with you is a comedy babe",
  "Any and every day with you is a miracle babe",
  "I’m here and I really really really want to hear your story babe… even the sad ones :(",
  "I really enjoy having my day accompanied by you :)",
  "You are amazing baby! don’t let nobody told you otherwise",
  "I really admire your values and your mind bby.. Thanks for being here ya",
  "I am rlly grateful that I have the chance to get to know someone as amazing as you :)",
  "What an honor it is to experience life by your side babe",
  "you don’t have to struggle alone sayang :((",
  "My amazing partner :)",
  "Thanks for all the amazing journey we’ve had till this point.. looking forward to what lies ahead, with you by my side :)",
  "I miss you bangett",
  "Mau tau rahasia gaa? aku enjoy bgt obrolan deep talk kita hehe.. apalagi yg ttg relationship!!",
  "How was your day? Chat aku sekarang juga ya kasih tau!!",
  "It is a luxury to experience your love and to shower you with mine",
  "semangat koas kamu! I know it’s really hard dan ini sesuatu yg baru buat kamu.. tapi aku percaya kamu bisa babe I’m rooting for you like always! ",
  "kamu cape ya tudei?:((( pasti di rumah sakit banyak jalan and pasti byk bgt yg harus dipelajarin ya :( ",
  "Aku mau kamu tau, kalo aku seneng banget tiap kali bisa denger kamu rest atau yoga atau creambath :) itu buat aku happy",
  "Aku seneng semua momen cinta2an, momen sedih2an, momen berantem2an, dan momen maaf2an,, sama kamu",
];
